//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedeSocial.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RedeSocial.Exceptions.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Pedido de amizade foi aceito !.
        /// </summary>
        public static string AmizadeAceita {
            get {
                return ResourceManager.GetString("AmizadeAceita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma solicitação de amizada para esse usuario !.
        /// </summary>
        public static string AmizadeDuplicada {
            get {
                return ResourceManager.GetString("AmizadeDuplicada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Os Usuarios já são Amigos !
        ///.
        /// </summary>
        public static string AmizadeExistente {
            get {
                return ResourceManager.GetString("AmizadeExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Pedido de amizade foi rejeitado !
        ///.
        /// </summary>
        public static string AmizadeRejeitada {
            get {
                return ResourceManager.GetString("AmizadeRejeitada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Amizade foi removida !.
        /// </summary>
        public static string AmizadeRemovida {
            get {
                return ResourceManager.GetString("AmizadeRemovida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Apenas o Destinatário pode aceitar o Pedido !.
        /// </summary>
        public static string ApenasDestinatario {
            get {
                return ResourceManager.GetString("ApenasDestinatario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Email ou a senha estão incorretos !.
        /// </summary>
        public static string CredenciaisInvalidas {
            get {
                return ResourceManager.GetString("CredenciaisInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esse email ja está cadastrado !
        ///.
        /// </summary>
        public static string EmailCadastrado {
            get {
                return ResourceManager.GetString("EmailCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pedido de Amizade não encontrado !
        ///.
        /// </summary>
        public static string PedidoNotFound {
            get {
                return ResourceManager.GetString("PedidoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuario não encontrado !
        ///.
        /// </summary>
        public static string UsuarioNotFound {
            get {
                return ResourceManager.GetString("UsuarioNotFound", resourceCulture);
            }
        }
    }
}
